
export const mockUsers = [
  {
    id: "1",
    email: "john.dev@example.com",
    name: "John Developer",
    role: "developer",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "jane.customer@example.com",
    name: "Jane Customer",
    role: "customer",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    email: "mike.dev@example.com",
    name: "Mike Developer",
    role: "developer",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
]

export const mockSoftware = [
  {
    id: "1",
    developerId: "1",
    name: "CodeEditor Pro",
    description: "Advanced code editor with AI assistance and collaboration features",
    version: "2.1.0",
    price: 49.99,
    isActive: true,
    downloadUrl: "https://example.com/downloads/codeeditor-pro",
    iconUrl: "/code-editor-icon.png",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "2",
    developerId: "1",
    name: "Database Manager",
    description: "Professional database management and visualization tool",
    version: "1.5.2",
    price: 79.99,
    isActive: true,
    downloadUrl: "https://example.com/downloads/db-manager",
    iconUrl: "/database-icon.png",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-15"),
  },
  {
    id: "3",
    developerId: "3",
    name: "Design Studio",
    description: "Creative design suite for UI/UX professionals",
    version: "3.0.1",
    price: 99.99,
    isActive: true,
    downloadUrl: "https://example.com/downloads/design-studio",
    iconUrl: "/design-tool-icon.png",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-28"),
  },
]

export const mockLicenses = [
  {
    id: "1",
    licenseKey: "CE-PRO-2024-ABCD-EFGH-IJKL",
    softwareId: "1",
    customerId: "2",
    status: "active",
    activatedAt: new Date("2024-02-05"),
    expiresAt: new Date("2025-02-05"),
    maxActivations: 3,
    currentActivations: 2,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: "2",
    licenseKey: "DB-MGR-2024-MNOP-QRST-UVWX",
    softwareId: "2",
    customerId: "2",
    status: "active",
    activatedAt: new Date("2024-02-10"),
    expiresAt: new Date("2025-02-10"),
    maxActivations: 1,
    currentActivations: 1,
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-10"),
  },
]

export const mockActivations = [
  {
    id: "1",
    licenseId: "1",
    deviceId: "device-001",
    deviceName: "Jane's MacBook Pro",
    ipAddress: "192.168.1.100",
    activatedAt: new Date("2024-02-05"),
    lastSeenAt: new Date("2024-03-01"),
    isActive: true,
  },
  {
    id: "2",
    licenseId: "1",
    deviceId: "device-002",
    deviceName: "Jane's Desktop PC",
    ipAddress: "192.168.1.101",
    activatedAt: new Date("2024-02-15"),
    lastSeenAt: new Date("2024-02-28"),
    isActive: true,
  },
]

export const mockPurchases = [
  {
    id: "1",
    customerId: "2",
    softwareId: "1",
    licenseId: "1",
    amount: 49.99,
    currency: "USD",
    status: "completed",
    paymentMethod: "credit_card",
    transactionId: "txn_1234567890",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "2",
    customerId: "2",
    softwareId: "2",
    licenseId: "2",
    amount: 79.99,
    currency: "USD",
    status: "completed",
    paymentMethod: "paypal",
    transactionId: "txn_0987654321",
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-08"),
  },
]

export const mockApiKeys = [
  {
    id: "1",
    developerId: "1",
    name: "Production API Key",
    key: "lk_prod_1234567890abcdef",
    isActive: true,
    lastUsedAt: new Date("2024-03-01"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-01"),
  },
  {
    id: "2",
    developerId: "1",
    name: "Development API Key",
    key: "lk_dev_abcdef1234567890",
    isActive: true,
    lastUsedAt: new Date("2024-02-28"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-28"),
  },
]
