version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_BROWSER_CORS_ALLOW_ORIGIN=http://localhost:3000
    command: server /data --console-address ":9001"
    networks:
      - baksho-net

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 admin 12345678) do
        echo 'Waiting for MinIO...';
        sleep 3;
      done;
      /usr/bin/mc mb -p myminio/file-bucket;
      /usr/bin/mc anonymous set public myminio/file-bucket;
      exit 0;
      "
    networks:
      - baksho-net

volumes:
  minio_data:

networks:
  baksho-net:
    driver: bridge
